spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: library_user
    password: password

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update


    database-platform: org.hibernate.dialect.PostgreSQLDialect


